import { createClient as createGeneratedClient, createConfig, type Client } from './gen/client/index.js'

import { attachOpenTelemetryInterceptors, type TelemetryOptions } from './telemetry.js'

// These exports are generated by `@hey-api/openapi-ts`.
export * from './gen/sdk.gen.js'
export type * from './gen/types.gen.js'

import {
  getScope,
  getTenancyCurrent,
  postAuthLogin,
  type Options
} from './gen/sdk.gen.js'

import type { GetScopeData, GetTenancyCurrentData, PostAuthLoginData } from './gen/types.gen.js'

export type ApiClient = {
  client: Client
  auth: {
    login: (
      body: PostAuthLoginData['body'],
      options?: Omit<Options<PostAuthLoginData>, 'body' | 'client'>
    ) => ReturnType<typeof postAuthLogin>
  }
  tenancy: {
    current: (options?: Omit<Options<GetTenancyCurrentData>, 'client'>) => ReturnType<typeof getTenancyCurrent>
  }
  scope: {
    list: (options?: Omit<Options<GetScopeData>, 'client'>) => ReturnType<typeof getScope>
  }
}

export type ApiClientConfig = {
  baseUrl: string
  telemetry?: TelemetryOptions
}

export function createClient(config: ApiClientConfig): ApiClient {
  const client = createGeneratedClient(
    createConfig({
      baseUrl: config.baseUrl
    })
  )

  if (config.telemetry?.enabled) {
    attachOpenTelemetryInterceptors(client, config.telemetry)
  }

  return {
    client,
    auth: {
      login: (body, options) =>
        postAuthLogin({
          ...options,
          client,
          body
        })
    },
    tenancy: {
      current: (options) =>
        getTenancyCurrent({
          ...options,
          client
        })
    },
    scope: {
      list: (options) =>
        getScope({
          ...options,
          client
        })
    }
  }
}
